# HIGHER ORDER FUNCTION
# 10 numbers

# def counttozero(n):
#     print(n)
#     if n == 0:
#         return
#     return counttozero(n-1)

# counttozero(10)

# sum of 10 numbers
# def sum(n):
#  if n == 1:
#   return 1
#  return n + sum(n-1)
# print (sum(10))


# scope of a variable
# scope - area in which it is recognised

# name = "risal" #global scope
# def myname():
#     name = "sreeja"
#     def nickname():
#      # local scope
#         #name = "yazil"
#         print(name)
#     #nickname()    
# myname()    












