# CREATE AN RPG GAME
# player vs enemy
# import random
# player=(input("enter your name")).lower()
# enemy =random.choice({'dragon','goblin','trollin'})
# playerhp= 100
# enemyhp = 100
# turn = 1
# while playerhp > 0  and enemyhp > 0 :
#      print(f"Turn{turn}")
#      print(f"{enemy}attacks player")
#      playerhp = playerhp - random.randiant(8,20)
#      print(f"player hp {playerhp}")
#      print(f"{player}strikes back")
#      enemyhp = enemyhp - random.randiant(8,20)
#      print(f"enemy hp {enemyhp}")
#      turn = turn+1
#      if playerhp < 0:
#           print(f"{enemy} won ")
#           break
#      elif enemyhp < 0:
#           print(f"{player}won")
#           break 